<?php

namespace AppBundle\Repository;

/**
 * DealRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DealRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCriteres($category, $town)
    {
        $qb = $this->createQueryBuilder('d')
            ->leftJoin('d.category', 'cat')
            ->addSelect('cat')
            ->leftJoin('d.entite', 'entite')
            ->addSelect('entite')
            ->leftJoin('entite.town', 'town')
            ->addSelect('town')
            ->where('d.active = :true')
            ->setParameter('true', true)
            ->andWhere('cat.id = :category')
            ->setParameter('category', $category)
            ->andWhere('town.id = :town')
            ->setParameter('town', $town)
        ;

        // On peut ajouter ce qu'on veut après
        $qb->orderBy('d.createdAt', 'DESC');

        return $qb
            ->getQuery()
            ->getResult()
        ;
    }
}
