# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path:          fos_user_security_login
                check_path:          fos_user_security_check
                default_target_path: /secure/safe-login

            logout:
                path:   fos_user_security_logout
                target: front_homepage
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mon-espace/utilisateurs, role: [ROLE_SUPER_ADMIN, ROLE_ADMIN] }
        - { path: ^/mon-espace/category, role: [ROLE_SUPER_ADMIN, ROLE_ADMIN] }
        - { path: ^/mon-espace/, role: [ROLE_SUPER_ADMIN, ROLE_ADMIN, ROLE_SELLER] }
